name: Publish Docs

on:                                                                                                                                                           
  push:                                                                                                                                                       
    branches:
      - master
    tags:                                                                                                                                                    
      - 'v*'

jobs:
  publish_docs:
    name: Publish Docs
    runs-on: ubuntu-latest
    steps:

    - name: Check out code
      uses: actions/checkout@v3
      with:
        fetch-depth: 0

    - name: Build documentation
      run: |
          TMP_DIR=$(mktemp -d)
          mkdir "$TMP_DIR"/latest

          WIKICMD_DOCS_BUILD_SAVE_AS="$TMP_DIR/latest/docs.tgz" make docs_build
          cd "$TMP_DIR/latest"
          tar xzvf ./docs.tgz
          rm docs.tgz
          cd -

          LATEST_VERSION=$(git describe --tags --abbrev=0 origin/master)
          git checkout "$LATEST_VERSION"
          WIKICMD_DOCS_BUILD_SAVE_AS="$TMP_DIR/docs.tgz" make docs_build
          cd "$TMP_DIR"
          tar xzvf ./docs.tgz
          rm docs.tgz
          cd -

          cp -r "$TMP_DIR" ./docs_html

    - name: Deploy docs
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./docs_html
